### PR TITLE
python: Verify that nosetest actually ran any tests

### PR DESCRIPTION
**Pull request by cgwalters**
There's a bug somewhere in this build process at least on RHEL7.1 that
I haven't debugged where nosetests doesn't load any of the tests.
nosetests by default will happily run no tests at all and report
success.

To ensure we detect the case where the tests don't run, configure
nosetests to use xunit output, and parse the result, verifying that
'ntests' is not zero.

### CODE REVIEW

**Comment by cgwalters** [comment]
Defer until glib one is debugged.

**Comment by jsilhan** [comment]
It check whether the tests ran but doesn't fix WHY nosetest were executed on wrong test dir. The path should be fixed.
@rholy , have you experienced this issue during porting to RHEL7?

**Comment by rholy** [comment]
I probably didn't pay attention... I'll check...

**Comment by cgwalters** [comment]
For reference I obviously agree the path should be fixed - the goal of this patch is to ensure the problem doesn't fly under the radar if it's happening to other people now, or in the future.

**Comment by cgwalters** [comment]
Applying this patch in the current Fedora 22 spec file:

```
diff --git a/hawkey.spec b/hawkey.spec
index 5bb1671..f8511bd 100644
--- a/hawkey.spec
+++ b/hawkey.spec
@@ -9,6 +9,7 @@ License:        LGPLv2+
 URL:           https://github.com/rpm-software-management/%{name}
 # git clone https://github.com/rpm-software-management/hawkey.git && cd hawkey && tito build --tgz
 Source0:       https://github.com/rpm-software-management/%{name}/archive/%{name}-%{version}.tar.gz
+Patch0:         0001-python-Verify-that-nosetest-actually-ran-any-tests.patch
 BuildRequires: libsolv-devel >= %{libsolv_version}
 BuildRequires: cmake expat-devel rpm-devel zlib-devel check-devel
 Requires:      libsolv%{?_isa} >= %{libsolv_version}
@@ -56,6 +57,7 @@ Python 3 bindings for the hawkey library.
 
 %prep
 %setup -q -n %{name}-%{version}
+%patch0 -p1
 
 rm -rf py3
 mkdir ../py3
```

causes the build to fail for me with the test failure.  Does that help someone who knows the Nose framework to use it to debug?

**Comment by cgwalters** [comment]
Don't mean to be too annoying on this issue, but I simply am not an expert in the Nose testing framework, and I feel it'd be a lot more efficient for someone who is to look at this.

**Comment by cgwalters** [comment]
I gave up and debugged this myself, turned out to be:

https://bugzilla.redhat.com/show_bug.cgi?id=1226753

**Comment by cgwalters** [comment]
Rebased and updated :arrow_up:

**Comment by jsilhan** [comment]
Great that you have found the problem. It's serious and It should be fixed in `python-rhev`. We cannot add this stuff to every application using nosetests in rhel. We will merge this if `python-rhev` is in RHEL base image and would cause hawkey RPM build not to be tested. Was the testing skipped during rhpkg scratch-build?

**Comment by jsilhan** [comment]
Ok, it couldn't hurt. Merged, thanks.

**Comment by rholy** [comment]
Actually it hurt. You've missed this line: https://github.com/rpm-software-management/hawkey/blob/master/hawkey.spec#L78
Could both of you try to build the RPMs before you submit/merge a patch please? At least if you change the routines that affect the build.

**Comment by cgwalters** [comment]
Ah, sorry...I'm building on RHEL7 so I don't have the Python 3 bindings.

How about this? https://github.com/rpm-software-management/hawkey/pull/98

**Pull request merged**
