### PR TITLE
spec: added valgrind test to %check

### PR DESCRIPTION
**Pull request by jsilhan**

### CODE REVIEW

**Comment by jsilhan** [comment]
retest this please

**Comment by cgwalters** [comment]
It seems like this would be better if it was integrated into the `Makefile`, something like:

`make valgrind-test` or so.

**Comment by rholy** [comment]
Yeah, that would be nice. I wouldn't have to remember the command then.
And what about simply adding it to "make test"?

**Comment by rholy** [comment]
Jenkins, retest this please.

**Comment by jsilhan** [comment]
Merged - added to `make test`

**Pull request closed without merging**
