### PR TITLE
maintain result map in query (RhBug:1049205)

### PR DESCRIPTION
**Pull request by jsilhan**
@dmach here is your requested feature. Do the benchmark test with your cases, please, to see if there's any speed improvement.

### CODE REVIEW

**Comment by rholy** [comment]
One drawback of this implementation is that when `apply` is called, you cannot find out what filters were applied. An alternative could be to (1) add the `computed` flag, (2) when `!computed` filter the current `result` BUT skip those solvables that have already been removed from the map and (3) not remove the filters then.

Anyway, if you insist on your implementation, I can live with that. Just few nitpicks:
- [ ] I'd leave the `if (q->result)` test in the `apply` method instead of moving it into the `init_result` method because I think that if someone calls `init_result` they expect `result` to be initialized
- [ ] I'd rename the `computed` flag to `applied` flag because I think that it fits better

**Comment by dmach** [comment]
I used fedora repo as an input and ran following test:
names = sorted(set([ i.name for i in sack.query().filter(arch=["x86_64", "noarch"])]))

**test#1 - get everything in 1 query**
list(sack.query().filter(arch=["x86_64", "noarch"]).filter(name=names))
result: 0.5s

**test#2 - make individual queries**
for i in names:
    list(sack.query().filter(arch=["x86_64", "noarch"]).filter(name=i))
result: 1.9s

**test#3 - make individual queries, use apply**
q = sack.query().filter(arch=["x86_64", "noarch"]).apply()
for i in names:
    list(q.filter(name=i))
result: 0.6s

**Conclusion:** this feature significantly boosts performance

**Comment by jsilhan** [comment]
> One drawback of this implementation is that once apply is called, you cannot find out what filters were applied.

That's a feature :) and purpose of this patch. The applied filters are no longer required so they are freed. Filters are saved in internal structure and shouldn't be accessed directly at all.

The rest is fixed and merged.

**Comment by rholy** [comment]
I don't see why they **shouldn't** be available...

**Comment by jsilhan** [comment]
You couldn't access them before. Nobody requested this feature and there would need to be also special C API for that (to not access to`_Filters` directly). I am not saying it is not useful but It's not worth the time to implement that now.

**Pull request closed without merging**
