### PR TITLE
speed up query filters

### PR DESCRIPTION
**Pull request by MichaelMraka**
skip items which has already been filtered out by previous filters

this change gains about 30% speed up for pungi

### CODE REVIEW

**Comment by rholy** [comment]
Let's note that OTOH this change limits these functions to be used just in AND filters (not that we have ORs... yet?...)... So far, they were general... I'm not saying that this is bad (or good), I'm just pointing to this fact.

**Comment by jsilhan** [comment]
Out of curiosity: Did you make some benchmarks? How many times it's faster for X filters applied and Y packages in the sack?

**Comment by MichaelMraka** [comment]
As for artificial test - It can be 0-50x faster depends on which filters you pick.
A real life test - pungi creating fedora compose runs 18 minutes originally and 12 mins with this fix.

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request merged**
