### PR TITLE
Goal

### PR DESCRIPTION
**Pull request by jsilhan**
needed for https://github.com/rpm-software-management/dnf/pull/304

### CODE REVIEW

**Comment by rholy** [comment]
Maybe you want to delete:

> Sacks cannot be deeply copied.

from the documentation then.

**Comment by jsilhan** [comment]
Sack still cannot be deeply copied. Deep copying of the goal only increment the reference of the sack.

**Comment by rholy** [comment]
Uh, sorry, I confused `Sack` and `Goal`. Sorry for the noise.

**Comment by mluscon** [comment]
Merged

**Pull request closed without merging**
