### PR TITLE
Implemantation of install weak methods

### PR DESCRIPTION
**Pull request by mluscon**

### CODE REVIEW

**Comment by rholy** [comment]
So, finally you prefer "optional" to "recommended" or "weak"?

**Comment by mluscon** [comment]
"recommended" sounds more related to package type and "weak" to solver internals from my point of view. What is your opinion @jsilhan, @rholy? I will add a documentation note after final decision.

**Comment by rholy** [comment]
I think that "weak" is almost the same as "recommended" since "recommends" is a type of a *weak* dependency. And I think that the new install method can be used also on packages, not just group members, thus all three variants sounds good to me. I prefer "recommended" or "weak" because they match the RPM terminology but "optional" is also OK.

**Comment by mluscon** [comment]
Updated changelog + weak replaced by optional in goal.c

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request closed without merging**
