### PR TITLE
CMake: Add option to control whether Python bindings and docs are built

### PR DESCRIPTION
**Pull request by Conan-Kudo**
For hawkey and libdnf to coexist on the same system, hawkey needs to not provide its older version of the python-hawkey bindings.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@ignatenkobrain ping?

**Comment by ignatenkobrain** [comment]
Just stop building hawkey. Completely. Finally.

**Comment by Conan-Kudo** [comment]
@ignatenkobrain Can't do that with tdnf and others still around...

**Comment by ignatenkobrain** [comment]
Hawkey is dead.

**Comment by Conan-Kudo** [comment]
Well, it can't be completely dead until F25 is EOL...

**Comment by ignatenkobrain** [comment]
Don't mix distro support and upstream.

**Pull request closed without merging**
