### PR TITLE
Link to GLib, use it in iutil

### PR DESCRIPTION
**Pull request by cgwalters**
I cannot think of any program that would want to use hawkey but not
use librepo.  In that case, the process is already linking to GLib.

Further, libhif is a consumer of both hawkey/librepo and uses GLib (as
well as GObject/GIO, but that's a distinct topic).  It would be
significantly more pleasant for libhif if hawkey offered APIs that
used GLib primitives (such as GError and GList).

This patch merely starts the process by changing the read_whole_file()
helper function in iutil to use g_file_get_contents().  There is
quite a bit more code that could be trimmed just in iutil.

A much more significant next step would be changing the public API,
e.g. for HyPackageList be a GList<HyPackage>.  But that discussion can
come after this.

### CODE REVIEW

**Comment by jsilhan** [comment]
You don't waste time to add the GLib dependency :). Of course the code is reduced and so more cleaner. Now we will not merge it just because of one function in utils. Let this PR be to discuss GLib based API and to stack there more GLib refactoring commits. GList looks handy.

**Comment by rholy** [comment]
...well, program that deals only with local repositories might not need librepo... but I agree that we don't need to reinvent the wheel... I'd just carefully think about the proper library... e.g. I wonder how much is glib used in librepo...

**Comment by cgwalters** [comment]
There's quite a number of other functions that could go away just in `iutil.c`, but here's a first step for `HyPackageList`.

**Comment by hughsie** [comment]
Using GLib in Hawkey would be awesome from my point of view.

**Comment by cgwalters** [comment]
Any further thoughts on this patch?  @rholy You were wondering about librepo and glib?  As far as I can see it's a pretty hard dependency.

**Comment by jsilhan** [comment]
WTR from today meeting:
* python API stays the same
* preserve the old C API and drop it later
* create new glib API, use the internally from hawkey and from libhif

I would suggest to get rid of using HyAdvisoryList, HyPackageLIst, HyStringArray from the start.

**Comment by cgwalters** [comment]
Rebased and updated to drop `HyStringArray` as well. I didn't do `HyAdvisoryList` - it's more deeply intertwined with the libsolv data structures, and isn't presently used often in libhif, whereas HyPackageList is used frequently.

**Comment by jsilhan** [comment]
Looks good, we should talk about the glib based API and deprecate the old one. Better sooner than later. I am not sure if we can manage to have the new API in RHEL7. Then getting changes there would be more complicated...

**Comment by rholy** [comment]
The file ```cmake/modules/FindGLIB2.cmake``` refers to a non-existent file ```COPYING-CMAKE-SCRIPTS```. Also I wonder how the BSD licence of the file affects the whole package. Should we mention somewhere that there is a BSD-licensed file in the hawkey package?

**Comment by rholy** [comment]
If "There may be a better way to do this...", can we do it the better way?

**Comment by rholy** [comment]
A note about all the API changes in ```COPYING``` is needed.

**Comment by rholy** [comment]
Also, I'm afraid that @hughsie will kill us if we don't bump soname with an API change again...

**Comment by hughsie** [comment]
Maybe not kill, but they'll be some hurt involved :) Thanks.

**Comment by cgwalters** [comment]
RE: `FindGLIB2.cmake`, i copied it from librepo (which I should have mentioned).  Some brief investigation reveals it's unnecessary: https://github.com/cgwalters/librepo/commit/827b719e2ba0c8bf15eab73bcb8c02f0ca5320a0

I'll update the PR here too.

**Comment by cgwalters** [comment]
Rebased with above changes, added an update to `doc/changes.rst`.

Also, I did not yet bump the soname - libhif works unchanged with this patchset.  Are there any known consumers of the hawkey C API other than libhif?

**Comment by cgwalters** [comment]
So of course rpm-ostree does use hawkey directly, and does call `hy_package_get_files`.  That's OK though, I can adapt obviously =)

Before we bump the soname though - any other breaking changes to land?

**Comment by rholy** [comment]
I think you can bump the soname (so we don't forget to do that) now and we can add some changes later if needed. Or did I miss something?

**Comment by rholy** [comment]
Could you please also add the necessary ```Requires``` to the spec file?

**Comment by rholy** [comment]
Could you please move the new ```changes.rst``` section to the bottom of the file so that the changes will be sorted?

**Comment by rholy** [comment]
Could you please prefix these commit messages with "apichange:":
* advisory: Remove hy_advisory_get_filenames 
* package: Convert hy_package_get_files() to gchar **, drop HyStringArray
(reference: https://github.com/rpm-software-management/dnf/wiki/Hacking#tags)

**Comment by rholy** [comment]
I got this warning:
```
hawkey/src/python/advisory-py.c:183:1: warning: ‘get_str_array’ defined but not used [-Wunused-function]
 get_str_array(_AdvisoryObject *self, void *closure)
```
Can you please remove this no more needed function?

**Comment by rholy** [comment]
Could you please fix (remove) the failing test?
(see https://github.com/rpm-software-management/hawkey#tests)

**Comment by rholy** [comment]
A total miracle for me is why no tool complains about this line: https://github.com/cgwalters/hawkey/blob/master/src/types.h#L34 since there is nothing called ```_HyPackageList``` in hawkey now...

**Comment by cgwalters** [comment]
- Re `_HyPackgeList`, it's quite normal in C to have unknown structures.  However, we can now change it to use `GPtrArray` explicitly so that callers more clearly know the equivalence.  Done.
- Failing test: They pass for me (config: unpacked build on RHEL7.1 WS, x86_64).  Can you pastebin any failures?
- RE `CMAKE_POLICY(SET CMP0003 NEW)` - I haven't addressed this comment yet, as I don't know of a better way, and while I've done some searching I haven't found a better way.  If anyone is or knows a CMake expert, that'd be useful.

All other comments should be addressed, thanks!

**Comment by rholy** [comment]
Thank you for the fixes and for the explanation. Here is the failing test: http://paste.fedoraproject.org/199401/

**Comment by rholy** [comment]
RE
FOREACH (NAME ${GLIB2_LIBRARIES})
  FIND_LIBRARY (LIBRARY NAMES ${NAME})
  MESSAGE(STATUS "Using libsolv bb at ${GLIB2_LIBRARIES} ${NAME} ${GLIB2_LIBRARY}")
  SET(GLIB2_LIBRARY ${GLIB2_LIBRARY} ${LIBRARY})
  MESSAGE(STATUS "Using libsolv bb at ${GLIB2_LIBRARIES} ${NAME} ${GLIB2_LIBRARY}")
  UNSET(LIBRARY CACHE)
ENDFOREACH(NAME)

**Comment by rholy** [comment]
Thank you for the fixes and for the explanation.

* re test: Here is the failing test: http://paste.fedoraproject.org/199401/
* re ```CMAKE_POLICY```: using a trial-and-error approach (I'm too lazy to read cmake documentation) I found that these works instead of setting the policy:
```
FOREACH (NAME ${GLIB2_LIBRARIES})
  FIND_LIBRARY (LIBRARY NAMES ${NAME})
  SET(GLIB2_LIBRARY ${GLIB2_LIBRARY} ${LIBRARY})
  UNSET(LIBRARY CACHE)
ENDFOREACH(NAME)
```
and:
```FIND_LIBRARY (GLIB2_LIBRARY NAMES glib-2.0)```
...assuming that ```GLIB2_LIBRARY``` is used in ```src/CMakeLists.txt``` instead of ```GLIB2_LIBRARIES```.
The first one is better because it uses the names given by the GLIB2 module. On the other hand, the other one is shorter. Hopefully the first one can be simplified...

But maybe the ```CMAKE_POLICY(... NEW)``` does the same implicitly and thus we probably don't need to bother with these.

**Comment by cgwalters** [comment]
So when I run `make test`, I see:

    $ make test
    Running tests...
    Test project /home/walters/src/github/rpm-software-management/hawkey
        Start 1: test_main
    1/2 Test #1: test_main ........................   Passed    0.24 sec
        Start 2: test_python
    2/2 Test #2: test_python ......................   Passed    0.77 sec
    
    100% tests passed, 0 tests failed out of 2
    
    Total Test time (real) =   1.02 sec
    
However...the `ARGS=-V` was quite a useful hint, with that I see:

    2: Test command: /home/walters/src/github/rpm-software-management/hawkey/tests/python/tests/run_nosetests.sh "-s" "/home/walters/src/github/rpm-software-management/hawkey/tests/python/tests"
    2: Test timeout computed to be: 9.99988e+06
    2: 
    2: ----------------------------------------------------------------------
    2: Ran 0 tests in 0.001s
    2: 
    2: OK
    2/2 Test #2: test_python ......................   Passed    0.36 sec

Okay so there are zero tests in this suite, which gets parented up to be 1 passed test =)

Why is that?  Well...I am a bit stuck debugging nose.  Here's some debug information:

    nose.suite: DEBUG: <nose.suite.ContextSuite context=tests.test_advisory> setup context <module 'tests.test_advisory' from '/home/walters/src/github/rpm-software-management/hawkey/tests/python/tests/test_advisory.pyc'>
    nose.suite: DEBUG: completed suite setup
    nose.suite: DEBUG: precache is [<nose.suite.ContextSuite context=None>]
    nose.suite: DEBUG: suite 45893584 (<nose.suite.ContextSuite context=None>) run called, tests: <generator object _get_wrapped_tests at 0x2c56aa0>
    nose.suite: DEBUG: suite 45893584 setUp called, tests: <generator object _get_wrapped_tests at 0x2c56af0>
    nose.suite: DEBUG: tests in 45893584?
    nose.suite: DEBUG: suite 45893584 has no tests
    nose.suite: DEBUG: precache is []
    nose.suite: DEBUG: context teardown
    nose.suite: DEBUG: No reason to teardown (was_setup? False was_torndown? False)
    nose.suite: DEBUG: context teardown
    
Is this maybe a Python 2 vs 3 issue or so?  I can set up a F22 container to test there too.

**Comment by jsilhan** [comment]
strange, try to build rpm package (`package/build-test-rpm`) - it should run python2 and python3 tests too

**Comment by rholy** [comment]
I have now idea what might be the cause. You can try running ```PYTHONPATH=build/src/python nosetests -s -v tests/python/tests/test_advisory.py``` whether an exception appears...

**Comment by jsilhan** [comment]
Next steps are:
* design new Glib hawkey API (add GError additional param to functions that can fail, ...)
* preserve the old API - it shoud be wrapper above Glib API, write deprecated message above this functions in header files
* don't use any of deprecated functions internally in hawkey

**Comment by jsilhan** [comment]
Hey @cgwalters , @hughsie , can we push new glib API only to RHEL7? We would not have to maintaint the old API in RHEL then. Should we wait for Glib changes? The deadline is June 23.

**Comment by cgwalters** [comment]
Ah...are you thinking this is a build-time option?   Or would it also be turned off in Fedora at some point?  (Feodra 23?)

**Comment by jsilhan** [comment]
Not build time option. The Glib changes will get to upstream. I though that we could have a in maint-rhel7 branch version not even exposing the old hawkey API (in case hawkey wasn't in RHEL7 before). So the Glib hawkey API could be available as soon as it will be complete and merged and the old API could be gone in next Fedora release or later.

**Comment by cgwalters** [comment]
Ok so some further real-world experience reveals that it would be nicer if we went beyond GLib - specifically to at least GObject.  See for example this comment https://github.com/projectatomic/rpm-ostree/pull/136#issuecomment-93755089

Right now refcounting at the hawkey level doesn't matter for `dnf` as Python provides its own refcounting.  But for C consumers, the fact that the `HyPackage` object has `const char *` pointers into the `HySack` object means that the only sane way to handle this if you're passing around `HyPackage` elsewhere is to refcount `HySack`.

Well, we could probably stick with GLib and leave `libhif` to be the GObject layer - potentially.  This is a larger discussion, I'd still like to land this baby step first.

**Comment by jsilhan** [comment]
I have never touched a GObject but if the python bindings will be lighter why not to to do that in C. Having it in `libhif` will be better idea if we can create python bindings to `libhif` and use it instead hawkey and librepo alone. We could then use the same code as you for package installation in DNF.

**Comment by cgwalters** [comment]
Ok, now that I was actually able to run the Nose tests (after debugging https://github.com/rpm-software-management/hawkey/pull/85 ), I've fixed the test regression, and rebased the patch set :arrow_up:

**Comment by cgwalters** [comment]
Overall this is still just a small step.  There's a lot of other potential things, such as considering going from GLib -> GObject.  This would:

 - Gaining refcounting on the objects
 - Reduce the rpm-ostree and libhif wrapping of objects

**Comment by jsilhan** [comment]
Looks good. This patches will go into hawkey 1.0 as there are many API breaks. Can you also use GErrors and erase `errno.[ch]` files to not make another API changes later on, please?

The function having assert(0) inside:
* filter_name2job
* filter_provides2job
* checksumt_l2h
* di_keyname2id
* reldep_keyname2id
* type2flags
* filter_reponame
* hy_query_clone
* repo_update_state
* repo_get_repodata
* repo_set_metadata
* hy_repo_set_string
* hy_repo_get_string

functions setting errno:
* abspath
* setarch
* hy_sack_load_repo
* hy_detect_arch
* list_results
* hy_goal_describe_problem
* hy_goal_write_debugdata
* hy_sack_repo_enabled
* hy_split_nevra
* load_ext
* load_filelists_cb
* load_presto_cb
* load_updateinfo_cb
* load_yum_repo
* hy_goal_write_debugdata
* mv
* read_whole_file
* write_main
* write_ext
* hy_sack_create
* hy_sack_load_system_repo
* hy_query_filter
* hy_query_filter_in
* hy_query_filter_num
* hy_query_filter_num_in
* hy_query_filter_package_in
* hy_query_filter_reldep
* hy_query_filter_reldep_in
* hy_query_filter_provides_in
* filter_arch2job
* hy_goal_upgrade_to_flags
* sltr2job
* replace_filter
* hy_selector_set

+ functions calling these functions

**Comment by Conan-Kudo** [comment]
@cgwalters In reply to your comment at the top of this thread (sorry, but I just saw it), the main reason that there's not a real urge to use hawkey without librepo is because hawkey isn't exposing libsolv's repository parsing capabilities. If someone were to extend hawkey to expose that functionality, then librepo would not be necessary in that case. But as it is, currently hawkey isn't that useful without librepo, I suppose.

**Comment by jsilhan** [comment]
Merged into branch https://github.com/rpm-software-management/hawkey/tree/glib . Libhif should merge that branch and hawkey repo will stay without glib dependency

**Comment by jsilhan** [comment]
btw compiling with clang it causes a lot of warnings. It seems clang doesn;t support glib macros and I am not sure if it could break things when it's compiled with other than gcc compiler.
```
...
In file included from /usr/include/glib-2.0/glib/glist.h:32:
/usr/include/glib-2.0/glib/gmem.h:83:58: warning: 
      unknown attribute '__alloc_size__' ignored
      [-Wunknown-attributes]
  ...n_bytes) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE...
                            ^
/usr/include/glib-2.0/glib/gmacros.h:67:45: note: 
      expanded from macro 'G_GNUC_ALLOC_SIZE'
#define G_GNUC_ALLOC_SIZE(x) __attribute__((__al...
                                            ^
...
```

**Pull request closed without merging**
