### PR TITLE
types: Revert unintentional ABI break in _hy_key_name_e

### PR DESCRIPTION
**Pull request by cgwalters**
Commit c5145b6816b1a771daa8c0282c34bd303a360f56 unintentionally
broke ABI by inserting these values into the middle of the enum.

Restore the old ABI by moving them to the end.

### CODE REVIEW

**Comment by rholy** [comment]
dnf-bot, ok to test.

**Comment by cgwalters** [comment]
See also followup patch :arrow_up:

**Comment by rholy** [comment]
@cgwalters, thanks, can you please also append `(RhBug:1247335)` to the end of the first line of the commit message?

**Comment by cgwalters** [comment]
Done.

**Comment by rholy** [comment]
Thank you!

**Comment by rholy** [comment]
Jenkins, retest this please.

**Pull request merged**
