### PR TITLE
introduced verify option for goal.run()

### PR DESCRIPTION
**Pull request by MichaelMraka**

### CODE REVIEW

**Comment by rholy** [comment]
Tests, please.

**Comment by rholy** [comment]
Please also note that in hawkey, we are using a really strange indentation policy. You should use tabs (and eventually 4 additional spaces if needed).

**Comment by MichaelMraka** [comment]
> Please also note that in hawkey, we follow a really strange indentation policy. You should use tabs (and eventually less than 8 additional spaces if needed).

Interesting. Can't we reindent whole hawkey with spaces to make it consistent with our other projects?

**Comment by rholy** [comment]
Ales was not a fan of doing that... IIRC the reason was that it would break ```git blame```.

**Comment by jsilhan** [comment]
I am for the reindentation for long time. My editor can't handle it effectively.

**Comment by MichaelMraka** [comment]
> I am for the reindentation for long time. My editor can't handle it effectively.
So... go ahead, reindent it :).

**Comment by MichaelMraka** [comment]
added tests

**Comment by rholy** [comment]
Thanks. So, why the goal in the test does not report the duplicates?

**Comment by MichaelMraka** [comment]
Duplicates aren't  goal problems, they don't break any requirements. Libresolv can detect it and suggest solution (i.e. removing of them) but these suggestions are not available in hawkey.

**Comment by rholy** [comment]
OK, then why did you add them to ```@System-broken.repo```? We should keep the fixtures as small as possible.

**Comment by MichaelMraka** [comment]
To have the test complete and be sure they are not reported as problems.

**Comment by rholy** [comment]
...If we would think about tests like this, you would have to add there every non-problematic package combination to be sure that they are not reported as problems... Unit tests should be done by the white-box method: HY_VERIFY is supposed to report conflicts and missing deps, there is no code that handles duplicates specially, so there is no need to test duplicates...

Document the new repository in ```tests/README```.

**Comment by PyDeq** [comment]
Also a Python test would be appreciated.

**Comment by MichaelMraka** [comment]
Here are python tests. Unfortunately they fail and I can't find out what's wrong. Can you help me debug the issue?

**Comment by rholy** [comment]
Thank you. So, it seems to me that there are several problems:

1. the method ```TestSack.load_test_repo``` calls ```_hawkey_test.load_repo(self, name, path, False)``` and we apparently want to call ```_hawkey_test.load_repo(self, name, path, True)```... so, I'm not sure how to implement loading of the broken system repo the best.... several solutions come to my mind:

    1. Add an new method (```TestSack.load_broken_system_repo```?)
    2. Add a new parameter to ```TestSack.load_system_repo```? Probably not since it should work as a mixin.
    3. Add a new attribute ```TestSack.system_repo_name``` and adjust ```TestSack.load_system_repo```
    4. Add a new parameter to ```TestSack.load_test_repo```? Probably not since it should work as a mixin.
    5. Add the problems to the ```@System``` repo since I assume that they shouldn't break the other tests.

    I'd prefer (5) or (1).
2. ```goal.run``` returns ```False``` in case of problems found
3. ```goal.list_installs``` raises an exception in case of problems found

**Comment by jsilhan** [comment]
Let's go with iv. option (adding `system=False` param) - IMO it's more versatile solution.

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request merged**
